# Generated by Django 4.1.2 on 2022-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_path', models.FileField(upload_to='songs/%Y/%m/%d/')),
            ],
        ),
    ]
