# Generated by Django 4.1.2 on 2022-10-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='music_player.playlist'),
        ),
    ]
