# Generated by Django 4.1.2 on 2022-10-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_songs_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='playlist',
        ),
        migrations.AddField(
            model_name='songs',
            name='playlist',
            field=models.ManyToManyField(default=1, to='music_player.playlist'),
        ),
    ]
