# Generated by Django 4.1.2 on 2022-11-07 07:34

from django.db import migrations, models
import music_player.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0004_remove_songs_playlist_songs_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='playlist',
            field=models.ManyToManyField(default=music_player.models.get_main_playlist, to='music_player.playlist'),
        ),
    ]
